In [4]:
import pandas as pd
import numpy as np
#Data cleaning and handling missing values
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
print(df)
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Department']=df['Department'].fillna(df['Department'].mode()[0])
print(df)

    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

In [5]:
import pandas as pd
import numpy as np
#Data cleaning and handling missing values
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
print("Original Dataset:")
print(df)
df_ffill = df.copy()
df_ffill.ffill(inplace=True)
df_ffill

Original Dataset:
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT

    Age Department
0  25.0         HR
1  30.0    Finance
2  30.0    Finance
3  40.0    Finance
4  35.0         IT

In [7]:
import pandas as pd
import numpy as np
#Data cleaning and handling missing values
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
print("Original Dataset:")
print(df)
df_ffill = df.copy()
df_ffill.bfill(inplace=True)
df_ffill

Original Dataset:
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT

    Age Department
0  25.0         HR
1  30.0    Finance
2  40.0    Finance
3  40.0         IT
4  35.0         IT

In [ ]:
import pandas as pd
import numpy as np
#Data cleaning and handling missing values
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
print("Original Dataset:")
print(df)
df_ffill = df.copy()
df_ffill.ffill(inplace=True)
df_ffill

In [9]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
print("Original Dataset:")
print(df)
df_drop_rows = df.dropna()
print("After droping rows:")
df_drop_rows

Original Dataset:
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
After droping rows:

    Age Department
0  25.0         HR
1  30.0    Finance
4  35.0         IT

In [10]:
df_drop_cols = df.dropna(axis=1)
print("After dropping columns:")
df_drop_cols

After dropping columns:

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [12]:
df_drop_rows = df.dropna(axis=0)
df_drop_rows

    Age Department
0  25.0         HR
1  30.0    Finance
4  35.0         IT

In [14]:
import pandas as pd
df = pd.DataFrame({
    'ID':[1,2,2,3,3,4],
    'Name':['Alice','Bob','Bob','David','David','Charlie'],
    'Age':[25,30,30,40,40,35],
})
print("Original Dataset:")
print(df)
df_exact = df.drop_duplicates()
print("After dropping duplicates:")
df_exact

Original Dataset:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   2      Bob   30
3   3    David   40
4   3    David   40
5   4  Charlie   35
After dropping duplicates:

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
3   3    David   40
5   4  Charlie   35

In [20]:
import pandas as pd
df = pd.DataFrame({
    'ID':[1,2,2,3,3,4],
    'Name':['Alice','Bob','Bob','David','David','Charlie'],
    'Age':[25,30,30,40,40,35],
})
print("Original Dataset:")
print(df)
df_subset_id = df.drop_duplicates(subset=['ID'])
print("After dropping duplicates of id:")
print(df_subset_id)
df_subset_name = df.drop_duplicates(subset=['Name'])
print("After dropping duplicates of name:")
print(df_subset_name)

Original Dataset:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   2      Bob   30
3   3    David   40
4   3    David   40
5   4  Charlie   35
After dropping duplicates of id:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
3   3    David   40
5   4  Charlie   35
After dropping duplicates of name:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
3   3    David   40
5   4  Charlie   35

In [23]:
import pandas as pd
df = pd.DataFrame({
    'Date':['2006-03-14','14/03/2006','March 14 2006','2006.14.03']
})
print("Original Dataset:")
print(df)
df['Date']=pd.to_datetime(df['Date'],errors='coerce').dt.strftime('%y-%m-%d')
print(df)

Original Dataset:
            Date
0     2006-03-14
1     14/03/2006
2  March 14 2006
3     2006.14.03
       Date
0  06-03-14
1       NaN
2       NaN
3       NaN

In [24]:
df_ffill = df.copy()
df_ffill.ffill(inplace=True)
df_ffill

       Date
0  06-03-14
1  06-03-14
2  06-03-14
3  06-03-14

In [25]:
df_ffill = df.copy()
df_ffill.bfill(inplace=True)
df_ffill

       Date
0  06-03-14
1       NaN
2       NaN
3       NaN

In [26]:
#Case normalization (lower/upper)
df=pd.DataFrame({'Name':['Alice','Bob','Charlie','David']})
df['Name_lower']=df['Name'].str.lower()
df['Name_upper']=df['Name'].str.upper()
print(df)

      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      Bob        bob        BOB
2  Charlie    charlie    CHARLIE
3    David      david      DAVID